export default {
  cloud: 'soundcloud',
  email: 'mail-outline',
  password: 'key',
  passwordConfirm: 'key-change',
  nutritions: 'nutritionix',
  workout: 'running',
  home: 'home',
  heart: 'heart-circle',
  chat: 'chat',
  goBack: 'ios-arrow-back',
  goForward: 'ios-arrow-forward',
  user: 'user',
  close: 'close',
  delete: 'delete-forever',
  phone: 'phone',
  edit: 'playlist-add',
  dots: 'dots-three-vertical',
  userEdit: 'user-edit',
  userAdd: 'user-plus',
  logout: 'power-off',
  facebook: 'facebook',
  instagram: 'instagram',
  body: 'ios-body',
  age: 'tree',
  success: 'checkcircle',
  city: 'location-city'
};
