export const ADD_DAILY_MEAL = 'ADD_DAILY_MEAL';
export const FETCH_DAILY_MEAL = 'FETCH_DAILY_MEAL';
export const SET_DAILY_MEAL_LIST = 'SET_DAILY_MEAL_LIST';
export const REMOVE_DAILY_MEAL = 'REMOVE_DAILY_MEAL';
export const ADD_DAILY_MEAL_RECIPE = 'ADD_DAILY_MEAL_RECIPE';
export const UPDATE_DAILY_MEAL_RECIPE = 'UPDATE_DAILY_MEAL_RECIPE';
export const REMOVE_DAILY_MEAL_RECIPE = 'REMOVE_DAILY_MEAL_RECIPE';
