export const SAVE_GALLERY = 'SAVE_GALLERY';
export const GET_GALLERY = 'GET_GALLERY';
export const SET_GALLERY = 'SET_GALLERY';
export const RESET_GALLERY = 'RESET_GALLERY';
export const DELETE_GALLERY = 'DELETE_GALLERY';
