export const FETCH_GROCERIES = 'FETCH_GROCERIES';
export const SET_GROCERIES = 'SET_GROCERIES';
export const ADD_GROCERIES = 'ADD_GROCERIES';
export const UPDATE_GROCERIES = 'UPDATE_GROCERIES';
export const DELETE_GROCERIES = 'DELETE_GROCERIES';
