export const GET_RECIPE_TYPES = 'GET_RECIPE_TYPES';
export const SET_RECIPE_TYPES = 'SET_RECIPE_TYPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const FETCH_RECIPE = 'FETCH_RECIPE';
export const SET_RECIPIES = 'SET_RECIPIES';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
