export const FETCH_TEMPLATES = 'FETCH_TEMPLATES';
export const SET_TEMPLATES = 'SET_TEMPLATES';
export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const ASSIGN_TEMPLATE_TO_CLIENT = 'ASSIGN_TEMPLATE_TO_CLIENT';
